### ISSUE TITLE
Converting all actors on map fails with error

### ISSUE THREAD

**Issue by Zamrod** [WBHarry/combat-hp-display#2]
If you click the convert all tokens on map button, you just get a large number of errors saying:

```
Error: [jqzbY4CXoA1Ho2yn] Invalid TokenData displayBars which must be a value in CONST.TOKEN_DISPLAY_MODES
    at TokenData._validateField (data.mjs:384:13)
    at TokenData.validate (data.mjs:275:14)
    at ClientDatabaseBackend._preUpdateDocumentArray (foundry.js:10197:18)
    at ClientDatabaseBackend._updateEmbeddedDocuments (foundry.js:10152:33)
    at ClientDatabaseBackend.update (backend.mjs:153:31)
    at async Function.updateDocuments (document.mjs:373:21)
    at async TokenDocument5e.update (document.mjs:456:21)
```

None of the tokens change.

![image](https://user-images.githubusercontent.com/12570777/166436887-f904a7ed-0ff8-4d91-ae8a-89d97c406d62.png)

This is using version 1.0.1 of the module.

**Comment by WBHarry** [comment]
Released version 1.0.2 fixing this issue! Thanks for pointing me to it. 💯
